# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa83111f64ac79bc5d37ed549c85a18b57d4db8f627b40f639a2f24413286d9af19d6ee8911b53fb7db798943641f7bf36d7ee8ec3eb1894410251b8a66c2f1

test:
  secret_key_base: ffda20bf8a22e5b0b40b4e2c16f3e01f3e4d506a275a2ee99c4cc578a4d14bb07a2404c756f21a7342d82ff87144d376e69f5aace6c932db143e77e4e41e3ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
